### ISSUE TITLE
action bug

### ISSUE THREAD

**Issue by ghamha1n** [alexdiliberto/ember-cli-transformicons#2]
action property have bug in the logic where change the value twice..

**Comment by alexdiliberto** [comment]
Are you able to provide any more information? Perhaps a `.gif` of the bug (http://recordit.co/) and a snapshot of your machine's `ember  version` command

**Comment by ghamha1n** [comment]
here my code where my actoin defined
every one click it toggle the value twice...

```
  actions: {
    toggleMenu:function(value){
      console.log(value);
      }
  }
// logging
// true
// false

```

**Comment by alexdiliberto** [comment]
I'm not able to reproduce this, I pulled up the demo page put a breakpoint in the action handler and it only gets hit once per click. Closing this issue, if you can provide a more concrete example, or an example repository then I could take a look at it.
